### ISSUE TITLE
大家注意力，这不是老师的项目，这和老师的样式根本不一样

### ISSUE THREAD

**Issue by yizhima** [chinadbo/vue-webpack-start#2]
仔细一看才知道是自己实现的。。。。。。。。。
你怎么不注明啊啊啊啊啊，讨厌😠

老师的项目地址:
https://github.com/Jokcy/vue-todo-tech/blob/master/src/todo/todo.vue

**Comment by chinadbo** [comment]
抱歉没有注明，这只是我当初个人的实现
